PREFIX :      <http://www.cattid.uniroma1.it/2012/arduinoDay#>
PREFIX tuio:  <http://www.swows.org/tuio#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX afn:   <http://jena.hpl.hp.com/ARQ/function#>
PREFIX fs:    <http://www.swows.org/function#>

CONSTRUCT {
  ?dataViewer
    a :DataViewer ;
    :group ?group ;
    :markerId ?markerId ;
    :state ?state ;
    :dependentData ?state, ?menuNewState .
  ?state
    :menuState ?menuNewState ;
    :sectionState ?sectionState ;
    :contentState ?contentState ;
    :stateCounter ?newStateCounter .
  ?menuNewState
    a :Dragging ;
    :cursor ?cursor .
}
WHERE {
  ?cursor
    :polaroid ?dataViewer ;
    :relativeX ?relativeX ;
    :relativeY ?relativeY .
  tuio:defaultSource tuio:updateTime ?updateTime .
  GRAPH :config {
    swi:GraphRoot
      :vpWidth ?vpWidth ;
      :vpHeight ?vpHeight ;
      :markerPosX ?markerPosX ;
      :markerPosY ?markerPosY ;
      :menuStartPos ?menuStartPos ;
      :baseDataPath ?baseDataPath
  } .
  GRAPH :viewerCurrState {
    ?dataViewer
      a :DataViewer ;
      :group ?group ;
      :markerId ?markerId ;
      :state ?state .
    ?state
      :menuState ?menuState ;
      :sectionState ?sectionState ;
      :contentState ?contentState ;
      :stateCounter ?stateCounter .
    ?menuState
      a :Popping ;
      :startPos ?menuStartPos ;
      :startTime ?updateTime
  } .
  BIND( ?stateCounter + 1 AS ?newStateCounter ) .
  BIND( ?updateTime - ?startTime AS ?delta ) .
  BIND( IF(?startPos < 0, IF (?delta * ?menuSpeed + ?startPos > 0, 0, ?delta * ?menuSpeed + ?startPos ),
        IF(?startPos < 120, IF (- ?delta * ?menuSpeed + ?startPos < 0, 0, - ?delta * ?menuSpeed + ?startPos ),
        IF(?startPos < 240, IF (?delta * ?menuSpeed + ?startPos > 240, 240, ?delta * ?menuSpeed + ?startPos ),
        IF (- ?delta * ?menuSpeed + ?startPos < 240, 240, - ?delta * ?menuSpeed + ?startPos ) ) ) ) 
    AS ?menuPosX ) .
  FILTER( ?relativeX >= ?menuPosX && ?relativeX <= ?menuPosX + 45.6 && ?relativeY >= ?57 && ?relativeY <= 102.9 ) .
}

