PREFIX :      <http://www.cattid.uniroma1.it/2012/arduinoDay#>
PREFIX tuio:  <http://www.swows.org/tuio#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX afn:   <http://jena.hpl.hp.com/ARQ/function#>

CONSTRUCT {
  ?dataViewer
    a :DataViewer ;
    :group ?group ;
    :markerId ?markerId ;
    :state ?state .
  ?state
    a :Picture ;
    :stateCount "1":xsd_integer ;
    :imgURI ?slideImageURI ;
}
WHERE {
  ?object a tuio:Object .
  ?object tuio:markerId ?markerId .
  tuio:defaultSource tuio:updateTime ?updateTime .
  GRAPH :config {
    swi:GraphRoot
      :menuStartPos ?menuStartPos ;
      :baseDataPath ?baseDataPath ;
      :baseSpeakerImgPath ?baseSpeakerImgPath .
  } .
  GRAPH :groupData {
    ?group
      a :Group ;
      :markerId ?markerId ;
      :mainPicture ?mainPicture .
  } .
  FILTER NOT EXISTS {
    GRAPH :viewerCurrState {
      ?dataViewer1
        a :DataViewer ;
        :markerId ?markerId .
    } .
  }
  BIND( CONCAT( ?baseSpeakerImgPath, ?mainPicture ) AS ?slideImageURI ) .
  BIND( URI(CONCAT( STR(:dataViewer_), MD5( STR(?object) ) ) ) AS ?dataViewer ) .
}

